// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_DlJOOaScC7zoeAx8vT5vXm8TrNqQ63c',
    appId: '1:261783605700:android:9a9ba1e03240ceb76c5491',
    messagingSenderId: '261783605700',
    projectId: 'hare-89094',
    databaseURL: 'https://hare-89094-default-rtdb.firebaseio.com',
    storageBucket: 'hare-89094.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0pv_LZaqd3t8Rwf8VnijIawrbueWzDDM',
    appId: '1:261783605700:ios:f6825edb910317ca6c5491',
    messagingSenderId: '261783605700',
    projectId: 'hare-89094',
    databaseURL: 'https://hare-89094-default-rtdb.firebaseio.com',
    storageBucket: 'hare-89094.firebasestorage.app',
    androidClientId:
        '261783605700-1d8em8fr0iuqr0c7s8i70edkvk7mqfbh.apps.googleusercontent.com',
    iosClientId:
        '261783605700-s3pchmpsqilc1vg1jptritva1eqbtp0d.apps.googleusercontent.com',
    iosBundleId: 'com.reen.customer',
  );
}
