/// Flutter icons CustomIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
library;
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData distance = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData findingDriver = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gps = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData maleFemale = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nothingFound = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pay = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pending = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData promoCode = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData recent = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData startMapPin = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData timeOrderHistoryScreen = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData time = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancelled = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData disableSign = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData childSeat = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData completed = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dateOrderHistoryScreen = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData destinationMapPin = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData addAddress = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData addressStoreResto = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cartOrderDetailsScreen = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendarAddCard = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData distanceStoreRestor = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emptyCart = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filterSorting = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData homeAddress = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_1 = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData offer = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData openingClosingHourHour = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData orderHistoryEmpty = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emergencyCall = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData otherAddress = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData store = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData timeDeliveryFlow = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData workAddress = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData addMoney = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData allServices = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transectionHistory = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whatsappIcon = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData myAccountChangePassword = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData myAccountEditProfile = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData myAccountEmergencyContact = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData myAccountHelpAndSupport = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cash = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData myAccountLiveChat = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notesToRestoStore = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData myAccountManageAddress = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData myAccountLogout = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData myAccountMyCoupons = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData myAccountPreferences = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tipToDriver = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData suitcaseProviderFlow = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inviteFriendVector = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cusine = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData myAccountInviteFriend = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData myAccountManageCard = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData orderPlaced = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData selectCardAddCard = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call_1 = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contactBook = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData myAccountNotificationList = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData myAccountChatWithAdmin = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData homeMain = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData liveChat = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profileMain = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet_1 = IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData package = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData deleteBin = IconData(0xe871, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icServiceTime = IconData(0xe8bc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
